name: Github Hosted Runner

on:
  workflow_dispatch:
  
jobs: 
  test:
     strategy:
        matrix:
          os : [ubuntu-latest,windows-latest,macos-latest]

     runs-on: ${{ matrix.os }}    

     steps:
       - name: OS name
         run : echo "This job is running on ${{ runner.os }}"

       - name: Hostname of Runner
         run: hostname
         shell: bash

       - name: User name
         run: echo " This job is executed by ${{ github.actor }}"
