name: PR check

on: 
  pull_request:
      branches:
        - main

      types: 
        - opened
        - synchronize
        
  schedule:
    - cron: "0 0 * * *"   # Runs every day at midnight UTC


jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps: 
      - name: Print PR branch
        run:  echo "PR check running for branch ${{ github.head_ref }}" 
