name: Secrets Check

on: 
  push: 
    branches: [main]

jobs:
  check-secret: 
  runs-on: ubuntu-latest

  steps: 
    - name: check if secret exists
      run: |
        if [ -n "${{secrets.MY_SECRET_MESSAGE}}" ]; then 
        echo "Secret is set: true"
        else
        echo "Secret is set: false"
        fi

    - name: Print secret
      run: echo "Secret  is: " ${{secrets.MY_SECRET_MESSAGE}}  
