name: Secret with Environment Variable 
on:
  workflow_dispatch:
  
jobs:
   docker-auth-check:
      runs-on: ubuntu-latest
      steps:
        - name: Use Secrets as Environment Variables
          env:
            DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
            DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}

          run: |
            echo "Docker Username is set: ${DOCKER_USERNAME:+true}"
            echo "Docker Token is set: ${DOCKER_TOKEN:+true}"
       
