name: Test CI 
on: workflow_dispatch

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Give Execute Permissions
        run: chmod +x ./system-info.sh

      - name: Run script
        run: ./system-info.sh
