name: Github Hosted Runner-preinstalled demo

on:
  workflow_dispatch:

jobs: 
  runner-demo:
    runs-on: ubuntu-latest
    steps:

       - name: Check Docker CLI version
         run: docker --version

       - name: Check Python Version
         run: python --version

       - name: Check Node Version
         run: node -v

       - name: Check Git Version
         run: git --version   
